import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, BarChart3, Check, HeartPulse, Package, Scale, Warehouse, Wheat } from 'lucide-react';
import CTA from '@/components/CTA';

const outcomes = [
  [Scale, 'Know performance early', 'Compare weigh-ins, gain, ADG, days on feed, and trends before sale day.'],
  [Wheat, 'Control the largest variable cost', 'Connect feed purchases, inventory, consumption, and cost to your operating structure.'],
  [HeartPulse, 'Keep health cost traceable', 'Record treatments, vaccinations, medicine use, and animal histories.'],
  [BarChart3, 'See margin before and after sale', 'Review recorded cost, expected value, realized revenue, margin, and ROI.'],
  [Package, 'Reduce stock blind spots', 'Monitor feed and medicine movement from purchase through consumption.'],
  [Warehouse, 'Operate across locations', 'Filter records by farm, shed, batch, ownership, and operating context.'],
];

const faq = [
  ['Is this feedlot management software?', 'Yes. The cattle workflow supports commercial fattening, beef finishing, feedlot, and related multi-animal operations. Terminology can be adapted during implementation.'],
  ['Can AnimalCare360 track cost per animal?', 'Direct animal costs can be tracked at animal level. Shared feed, labour, and overhead depend on the batch, pen, farm, or allocation method used by the operation.'],
  ['Does it support partner-owned or Palai cattle?', 'CattlePro includes ownership, allocation, expense, ledger, settlement, and profit-sharing workflows for applicable partner models. Final setup should match your local agreements and accounting requirements.'],
  ['Can we start with one farm?', 'Yes. An operation can begin with one location and add more farms, sheds, users, and workflows as adoption grows.'],
];

export default function CattleFatteningSoftwarePage() {
  return <div>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'AnimalCare360 Cattle Fattening Management Software', applicationCategory: 'BusinessApplication', operatingSystem: 'Web, Android', url: 'https://www.animalcare360.com/cattle-fattening-software', description: 'Software for managing cattle purchase, feed, weight, health, inventory, expenses, sale, and profitability.', featureList: outcomes.map(([, title]) => title) }) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) }) }} />
    <section className="border-b border-brand-border bg-white"><div className="section-container grid min-h-[610px] items-center gap-12 lg:grid-cols-2">
      <div><p className="text-xs font-bold uppercase text-brand-primary">Commercial cattle operations</p><h1 className="mt-4 text-4xl font-bold leading-tight text-brand-navy md:text-5xl">Cattle fattening management software built around cost and gain.</h1><p className="mt-6 text-lg leading-8 text-brand-muted">Control the operating chain from cattle purchase through feed, weight, health, expenses, inventory, sale, and settlement. Understand how performance affects margin before it becomes a surprise.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/cattle-fattening-profit-calculator" className="btn-primary inline-flex items-center justify-center gap-2 px-7 py-3.5">Calculate Your Cattle Profit <ArrowRight className="h-5 w-5" /></Link><Link href="/demo" className="inline-flex items-center justify-center rounded-lg border border-brand-border px-7 py-3.5 font-bold text-brand-navy">Book a Demo</Link></div></div>
      <figure className="overflow-hidden rounded-lg border border-brand-border bg-brand-background shadow-card"><div className="relative aspect-[16/10]"><Image src="/dashboard-finance.png" alt="AnimalCare360 finance dashboard for cattle operations" fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-top" /></div><figcaption className="border-t border-brand-border bg-white p-4 text-sm text-brand-muted">AnimalCare360 product view: financial and operating records.</figcaption></figure>
    </div></section>

    <section className="bg-brand-background"><div className="section-container"><div className="max-w-3xl"><p className="text-xs font-bold uppercase text-brand-primary">The management question</p><h2 className="mt-3 text-3xl font-bold text-brand-navy md:text-4xl">Which animals are creating margin, and which are consuming it?</h2><p className="mt-5 leading-7 text-brand-muted">Commercial operators often have purchase and sale records but incomplete visibility into cost of gain, treatment cost, inventory movement, slow performance, shared overhead, and partner settlement. AnimalCare360 builds that picture from daily records instead of end-of-cycle guesswork.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{outcomes.map(([Icon, title, text]) => { const OutcomeIcon = Icon as typeof Scale; return <div key={title as string} className="rounded-lg border border-brand-border bg-white p-6"><OutcomeIcon className="h-6 w-6 text-brand-primary" /><h3 className="mt-5 font-bold text-brand-navy">{title as string}</h3><p className="mt-2 text-sm leading-6 text-brand-muted">{text as string}</p></div>; })}</div></div></section>

    <section className="border-y border-brand-border bg-white"><div className="section-container"><div className="max-w-2xl"><p className="text-xs font-bold uppercase text-brand-primary">Operating model</p><h2 className="mt-3 text-3xl font-bold text-brand-navy">One economic record from purchase to settlement</h2></div><div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-brand-border bg-brand-border sm:grid-cols-2 lg:grid-cols-4">{[['01', 'Register', 'Identity, source, ownership, purchase weight, and purchase cost.'], ['02', 'Operate', 'Feed, health, medicine, inventory, labour, and farm expenses.'], ['03', 'Measure', 'Weight gain, ADG, cost of gain, expected value, and exceptions.'], ['04', 'Settle', 'Sale, buyer, payments, partner balances, realized margin, and ROI.']].map(([n, title, text]) => <div key={title} className="bg-white p-6"><span className="text-xs font-bold text-brand-primary">{n}</span><h3 className="mt-4 font-bold text-brand-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-brand-muted">{text}</p></div>)}</div></div></section>

    <section className="bg-brand-background"><div className="section-container grid gap-10 lg:grid-cols-2 lg:items-center"><figure className="overflow-hidden rounded-lg border border-brand-border bg-white"><div className="relative aspect-[16/10]"><Image src="/dashboard-palai.png" alt="AnimalCare360 ownership and partner management dashboard" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-top" /></div></figure><div><p className="text-xs font-bold uppercase text-brand-primary">Ownership and partner workflows</p><h2 className="mt-3 text-3xl font-bold text-brand-navy">Keep operating responsibility and financial ownership clear.</h2><p className="mt-5 leading-7 text-brand-muted">For investor-backed, partner-owned, or Palai-style operations, record ownership allocation, expenses, ledgers, outstanding balances, settlement, and profit sharing. The software supports record keeping; contractual, legal, and tax treatment must follow your applicable agreements and jurisdiction.</p><ul className="mt-6 space-y-3 text-sm text-brand-navy">{['Animal and batch ownership', 'Partner allocation and ledgers', 'Expense and payment records', 'Settlement and profit-sharing records'].map((item) => <li key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-brand-primary" />{item}</li>)}</ul></div></div></section>

    <section className="border-t border-brand-border bg-white"><div className="section-container max-w-4xl"><h2 className="text-3xl font-bold text-brand-navy">Cattle fattening software questions</h2><div className="mt-7 divide-y divide-brand-border border-y border-brand-border">{faq.map(([q, a]) => <div key={q} className="py-6"><h3 className="font-bold text-brand-navy">{q}</h3><p className="mt-2 text-sm leading-6 text-brand-muted">{a}</p></div>)}</div></div></section>
    <CTA title="See how your cattle records become operating decisions." subtitle="Bring a recent batch example to a guided demonstration. We will map purchase, feed, weight, health, cost, and sale records to the workflow." />
  </div>;
}
